/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Entrad;

import Chefa.BenvindChefa;
import Entrad.menuprincipal;
import TradutorDAO.AcessoDAO;
import conexao.conexaoBanco;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;

/** 
 *
 * @author User1
 */
public class iniciar extends javax.swing.JFrame {

    

    /**
     * Creates new form iniciar
     */
    public iniciar() {
        
        initComponents();
        labLoginIncorreto.setVisible(false); // MENSAGEM DE ERRO não visivel
        
        jPanel1.setBackground(Color.getHSBColor(255,10,25)); // dando cor a aos objetos
        txlogin.setBackground(Color.cyan);
        txsenha.setBackground(Color.cyan);
        btInicio.setBackground(Color.cyan);
        jcbxFunc.setBackground(Color.cyan);
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btInicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txlogin = new javax.swing.JTextField();
        txsenha = new javax.swing.JTextField();
        labLoginIncorreto = new javax.swing.JLabel();
        jcbxFunc = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BEM VINDOS");

        btInicio.setBackground(new java.awt.Color(153, 255, 204));
        btInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btInicio.setText("INICIAR");
        btInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioActionPerformed(evt);
            }
        });

        jLabel2.setText("Login:");

        jLabel3.setText("Senha:");

        txlogin.setBackground(new java.awt.Color(102, 255, 204));

        txsenha.setBackground(new java.awt.Color(153, 255, 204));

        labLoginIncorreto.setForeground(new java.awt.Color(255, 51, 51));
        labLoginIncorreto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLoginIncorreto.setText("LOGIN OU SENHA INCORRETOS, FAVOR CONSERTAR.");

        jcbxFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Função", "Funcionario", "Cliente" }));
        jcbxFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbxFuncMouseClicked(evt);
            }
        });
        jcbxFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(labLoginIncorreto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcbxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jcbxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(labLoginIncorreto)
                .addGap(18, 18, 18)
                .addComponent(btInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioActionPerformed
       
        Color cl = Color.getHSBColor(408, 200, 211); // DAR UMA COR A VARIAVEL DO TIPO COR
        
        Connection con = conexaoBanco.AbrirConexao();//ABRIR CONEXÃO//
        
        AcessoDAO acDao = new AcessoDAO(con); 
        
        String v =txlogin.getText();
        int cat = jcbxFunc.getSelectedIndex(); // obtem dados importantes para o funcionamento do sistema
        String Login = txlogin.getText();
        String  senha = txsenha.getText();
        
        menuprincipal MenPrinc = new menuprincipal();

        if(cat == 0){ // se a JcomboBox não tiver sido selecionada ou tiver selecionado o nome função faça isso
        
            if( v != "5481" ){ // Se o login for diferente de 5481 continui
            
                acDao.Logar(Login, senha); // pesquisa pelos dados de login e senha
            
                    if(acDao.g == 2){ // g é uma variavel de controle que ganha ou perde 
                        //valor a medida em que a pesquisa por ligin e senha é feita
                        // Se g = 2 é porque o login e senha esta certo
                        // Se g = 0 é porque tem coisa errada
                        
                        JOptionPane.showMessageDialog(null, "Acesso Permitido","Acesso:", JOptionPane.CLOSED_OPTION); //mensagem de acesso 
                        MenPrinc.setVisible(true);
                        this.dispose();
                
                   }if(Integer.parseInt(txlogin.getText()) == 5481){  //1 Se g não for igual a 2 mais o login for igual a 5481
                       // o sistema abre para o acesso a superiores que conta com uma tabela particular no banco de dados
                       
                        JOptionPane.showMessageDialog(null, "Acesso Para Superiores","Acesso:", JOptionPane.CLOSED_OPTION);// mensagem chique
                        BenvindChefa bmvch = new BenvindChefa();
                        bmvch.setVisible(true);
                        this.dispose();
      
          }   
        else{  //4
            JOptionPane.showMessageDialog(null, "Acesso Negado","Acesso:", JOptionPane.ERROR_MESSAGE); // se tudo der ruim até agora 
            // a mensagem de erro aparece
                labLoginIncorreto.setVisible(true);
              //  System.out.println("login:  " + Login+ "  senha:  "+senha);
        }}}

        if(cat == 1){// se selecionarem funcionario na jcomboBox faça o seguinte
            if( v != "5481" ){// se login for diferente do codigo prosiga
            
                acDao.Logar(Login, senha); //pesquisa o login e senha
            
                    if(acDao.g == 2){ // mesma coisa do outro
                    
                        JOptionPane.showMessageDialog(null, "Acesso Permitido","Acesso:", JOptionPane.CLOSED_OPTION);
                        MenPrinc.setVisible(true);
                        this.dispose();
        }   else{  //4 
            JOptionPane.showMessageDialog(null, "Acesso Negado","Acesso:", JOptionPane.ERROR_MESSAGE);
                labLoginIncorreto.setVisible(true);
                
            
        }}
           else{  //4
            JOptionPane.showMessageDialog(null, "Acesso Negado","Acesso:", JOptionPane.ERROR_MESSAGE);
                labLoginIncorreto.setVisible(true);
                
            
        }}
        if(cat == 2){// se selecionarem cliente faça o resto
           if( v != "5481" ){// mesma coisa dos outros
            
            acDao.Logar(Login, senha);
            
                if(acDao.g == 2){
                    
                JOptionPane.showMessageDialog(null, "Acesso Permitido","Acesso:", JOptionPane.CLOSED_OPTION);
                MenPrinc.setVisible(true);
                this.dispose();
                
        }   else{  //4
            JOptionPane.showMessageDialog(null, "Acesso Negado","Acesso:", JOptionPane.ERROR_MESSAGE);
                labLoginIncorreto.setVisible(true);
                System.out.println("login:  " + Login+ "  senha:  "+senha);
            
        }}   else{  //4
            JOptionPane.showMessageDialog(null, "Acesso Negado","Acesso:", JOptionPane.ERROR_MESSAGE);
                labLoginIncorreto.setVisible(true);
                System.out.println("login:  " + Login+ "  senha:  "+senha);
            
        }
        }
    }//GEN-LAST:event_btInicioActionPerformed

    private void jcbxFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbxFuncMouseClicked

        
    }//GEN-LAST:event_jcbxFuncMouseClicked

    private void jcbxFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxFuncActionPerformed
       
                int cat = jcbxFunc.getSelectedIndex(); // pega o numero referente ao que
                //foi selecionado na jcomboBox
               
            // de acordo com cada seleção as cores do projeto mudaram 
        
                if(cat == 0){ //normal ou função 
        
            jPanel1.setBackground(Color.getHSBColor(255,10,25));
            txlogin.setBackground(Color.cyan);
            txsenha.setBackground(Color.cyan);
            btInicio.setBackground(Color.cyan);
            jcbxFunc.setSelectedIndex(cat);
            jcbxFunc.setBackground(Color.cyan);
              
                }
            if(cat == 1){ //funcionario
        
            jPanel1.setBackground(Color.gray);
            txlogin.setBackground(Color.LIGHT_GRAY);
            txsenha.setBackground(Color.LIGHT_GRAY);
            btInicio.setBackground(Color.LIGHT_GRAY);
            jcbxFunc.setSelectedIndex(cat);
            jcbxFunc.setBackground(Color.LIGHT_GRAY);
                }
                if(cat == 2){// cliente
 /*
            laranja meio escuro = (234,234,50), (255,202,100), (255,202,135)
            Amarelo claro = (224,224,10)
            Cor de pele = 224,50,224)
            um azul meio verde super escuro (255,202,202)
            Vermelho super escuro = (255,202,120)
                    
 */

            jPanel1.setBackground(Color.getHSBColor(255,150,25)); 
            txlogin.setBackground(Color.MAGENTA);
            txlogin.setForeground(Color.BLACK);
            txsenha.setBackground(Color.MAGENTA);
            txsenha.setForeground(Color.BLACK);
            btInicio.setBackground(Color.MAGENTA);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            jLabel3.setForeground(Color.BLACK);
            jcbxFunc.setSelectedIndex(cat);
            jcbxFunc.setBackground(Color.MAGENTA);
                }
    }//GEN-LAST:event_jcbxFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbxFunc;
    private javax.swing.JLabel labLoginIncorreto;
    private javax.swing.JTextField txlogin;
    private javax.swing.JTextField txsenha;
    // End of variables declaration//GEN-END:variables
}
