/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Atualisas;

import Entrad.menuprincipal;
import TradutorDAO.AcessoDAO;
import TradutorDAO.PessoaDAO;
import TradutorDAO.funcionarioDAO;
import classes.Pessoa;
import classes.cliente;
import classes.endereco;
import classes.funcionario;
import conexao.conexaoBanco;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author Vivian Raquel                                                                                                                                                                                                                                                                                                                                                    
 */
public class AtuFuncionario extends javax.swing.JFrame {

    ArrayList<endereco> endereco = new ArrayList<>();
    ArrayList<Pessoa> Pessoa = new ArrayList<>();
    ArrayList<funcionario> funcionario = new ArrayList<>();
    
    public int G = 0;
    /**
     * Creates new form AtuFuncionario
     */
    public AtuFuncionario() {
        initComponents();
        PessoaDAO psd = new PessoaDAO();
        endereco end = new endereco();
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        painelcadastro = new javax.swing.JPanel();
        labelcadastrocliente = new javax.swing.JLabel();
        labelnomeclient = new javax.swing.JLabel();
        txlDnasci = new javax.swing.JLabel();
        labelcpf = new javax.swing.JLabel();
        labeltelefone = new javax.swing.JLabel();
        labelcidade = new javax.swing.JLabel();
        labelUR = new javax.swing.JLabel();
        labelEndere = new javax.swing.JLabel();
        labelBairr = new javax.swing.JLabel();
        labelNumeResi = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        txnome = new javax.swing.JTextField();
        txdatadn = new javax.swing.JTextField();
        txcpf = new javax.swing.JTextField();
        txtc = new javax.swing.JTextField();
        txur = new javax.swing.JTextField();
        txbairro = new javax.swing.JTextField();
        txcidade = new javax.swing.JTextField();
        txendereco = new javax.swing.JTextField();
        txnr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txcep = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txsalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txturno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txMatricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        btatualizar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelcadastro.setBackground(new java.awt.Color(255, 153, 255));
        painelcadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelcadastrocliente.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labelcadastrocliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcadastrocliente.setText(" PESQUISA DE FUNCIONARIO");

        labelnomeclient.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelnomeclient.setText("NOME:");

        txlDnasci.setText("DATA DE NASCIMENTO:");

        labelcpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcpf.setText("CPF/CNPJ:");

        labeltelefone.setText("TELEFONE CELULAR:");

        labelcidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcidade.setText("CIDADE:");

        labelUR.setText("UR:");

        labelEndere.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEndere.setText("ENDEREÇO:");

        labelBairr.setText("BAIRRO:");

        labelNumeResi.setText("NUMERO RESIDENCIAL:");

        btPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        btPesquisar.setText("pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        txnome.setEditable(false);
        txnome.setBackground(new java.awt.Color(204, 204, 204));

        txdatadn.setEditable(false);
        txdatadn.setBackground(new java.awt.Color(204, 204, 204));
        txdatadn.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txdatadnCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        txcpf.setBackground(new java.awt.Color(204, 204, 204));

        txtc.setEditable(false);
        txtc.setBackground(new java.awt.Color(204, 204, 204));

        txur.setEditable(false);
        txur.setBackground(new java.awt.Color(204, 204, 204));

        txbairro.setEditable(false);
        txbairro.setBackground(new java.awt.Color(204, 204, 204));

        txcidade.setEditable(false);
        txcidade.setBackground(new java.awt.Color(204, 204, 204));
        txcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcidadeActionPerformed(evt);
            }
        });

        txendereco.setEditable(false);
        txendereco.setBackground(new java.awt.Color(204, 204, 204));

        txnr.setEditable(false);
        txnr.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("CEP:");

        txcep.setEditable(false);
        txcep.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("salario:");

        txsalario.setEditable(false);
        txsalario.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Turno:");

        txturno.setEditable(false);
        txturno.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Matricula:");

        txMatricula.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("Codigo:");

        txCodigo.setBackground(new java.awt.Color(204, 204, 204));

        btatualizar.setBackground(new java.awt.Color(153, 153, 153));
        btatualizar.setText("atualizar");
        btatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btatualizarActionPerformed(evt);
            }
        });

        btexcluir.setBackground(new java.awt.Color(153, 153, 153));
        btexcluir.setText("excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelcadastroLayout = new javax.swing.GroupLayout(painelcadastro);
        painelcadastro.setLayout(painelcadastroLayout);
        painelcadastroLayout.setHorizontalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelcadastrocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelEndere, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(labelcidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelBairr))
                                .addComponent(labelnomeclient, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txlDnasci)
                                    .addComponent(btPesquisar, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txendereco)
                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addComponent(txturno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(labelUR)
                                        .addGap(9, 9, 9)
                                        .addComponent(txur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelNumeResi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txnr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txnome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txcep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                            .addComponent(txbairro, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(labeltelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addComponent(txdatadn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(63, 63, 63)
                                                .addComponent(jLabel5))
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(btatualizar)))
                                        .addGap(18, 18, 18)
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addComponent(btexcluir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                                .addComponent(jButton1))
                                            .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 14, Short.MAX_VALUE))))
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addComponent(labelcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelcadastroLayout.setVerticalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelcadastrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcpf)
                    .addComponent(txcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnomeclient))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUR)
                    .addComponent(txur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeResi)
                    .addComponent(txnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcidade)
                    .addComponent(txcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEndere)
                            .addComponent(txendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBairr)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelcadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltelefone)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txlDnasci)
                    .addComponent(txdatadn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btatualizar)
                    .addComponent(btexcluir)
                    .addComponent(jButton1)
                    .addComponent(btPesquisar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        txbairro.setText("");
        txcep.setText("");
        txcidade.setText("");
        txdatadn.setText("");
        txendereco.setText("");
        txnome.setText("");
        txnr.setText("");
        txsalario.setText("");
        txtc.setText("");
        txturno.setText("");
        txur.setText("");

       
        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);
        PessoaDAO psd = new PessoaDAO();
        funcionarioDAO fund = new funcionarioDAO();
 
        funcionario fun  = new funcionario();
        Pessoa p  = new Pessoa();
        endereco end = new endereco();
        

        G=1;
        fun = fund.buscarFuncionario(txcpf.getText());
        p = psd.buscarPessoa (txcpf.getText());
        end = psd.buscarEnderecoPes (txcpf.getText());
        
        txcpf.setText(p.getCpf());
        txdatadn.setText(p.getDatanasc());
        txnome.setText(p.getNome());
        txtc.setText(p.getTelefone());
        
        txcpf.setText(fun.getFkcpf());
        txMatricula.setText(fun.getMatricula());
        txsalario.setText(fun.getSalario()+"");
        txturno.setText(fun.getTurno());
        
        txCodigo.setText(end.getCodigo());
        txbairro.setText(end.getBairro());
        txcep.setText(end.getCep());
        txcidade.setText(end.getCidade());
        txcpf.setText(end.getFkcpf()+"");
        txendereco.setText(end.getEndereco());
        txnr.setText(end.getNumerResiden());
        txur.setText(end.getUr());
        
        endereco.add(end);//cria uma "lista" com todos os dados p.set{...}
        funcionario.add(fun);
        Pessoa.add(p);
        
        txbairro.setEditable(true);
        txcep.setEditable(true);
        txcidade.setEditable(true);
        txdatadn.setEditable(true);
        txendereco.setEditable(true);
        txnome.setEditable(true);
        txnr.setEditable(true);
        txsalario.setEditable(true);
        txtc.setEditable(true);
        txturno.setEditable(true);
        txur.setEditable(true);
 

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void txdatadnCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txdatadnCaretPositionChanged

    }//GEN-LAST:event_txdatadnCaretPositionChanged

    private void txcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       menuprincipal mp =new menuprincipal();
       mp.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btatualizarActionPerformed
        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);
        Pessoa p = new Pessoa();
        funcionarioDAO fund = new funcionarioDAO();

        funcionario fc = new funcionario();
        endereco en = new endereco();
        PessoaDAO psd = new PessoaDAO();

        p.setCpf(txcpf.getText());
        p.setDatanasc(txdatadn.getText());
        p.setTelefone(txtc.getText());
        p.setNome(txnome.getText());


        en.setBairro(txbairro.getText());
        en.setCep(txcep.getText());
        en.setCidade(txcidade.getText());
        en.setCodigo(txCodigo.getText());
        en.setEndereco(txendereco.getText());       
        en.setFkcpf(txcpf.getText()); 
        en.setNumerResiden(txnr.getText());       
        en.setUr(txur.getText()); 

        fc.setFkcpf(txcpf.getText());
        fc.setMatricula(txMatricula.getText()); 
        fc.setSalario(Float.parseFloat(txsalario.getText()));     
        fc.setTurno(txturno.getText());

        Pessoa.add(p);
        endereco.add(en);
        funcionario.add(fc);

        psd.AtualEnd(en);
        psd.AtualPessoa(p);
        fund.AtualFuncio(fc);
        
    }//GEN-LAST:event_btatualizarActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed

        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO(con);
        funcionarioDAO fund = new funcionarioDAO();
        Pessoa p = new Pessoa();
       

        p.setCpf(txcpf.getText());
      
        if(fund.ExcluirFincio(p.getCpf())){
       
            txbairro.setText("");
            txcep.setText("");
            txcidade.setText("");
            txdatadn.setText("");
            txendereco.setText("");
            txnome.setText("");
            txnr.setText("");
            txsalario.setText("");
            txtc.setText("");
            txturno.setText("");
            txur.setText("");
            txMatricula.setText("");
            txCodigo.setText("");
        }
    }//GEN-LAST:event_btexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtuFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btatualizar;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelBairr;
    private javax.swing.JLabel labelEndere;
    private javax.swing.JLabel labelNumeResi;
    private javax.swing.JLabel labelUR;
    private javax.swing.JLabel labelcadastrocliente;
    private javax.swing.JLabel labelcidade;
    private javax.swing.JLabel labelcpf;
    private javax.swing.JLabel labelnomeclient;
    private javax.swing.JLabel labeltelefone;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txMatricula;
    private javax.swing.JTextField txbairro;
    private javax.swing.JTextField txcep;
    private javax.swing.JTextField txcidade;
    private javax.swing.JTextField txcpf;
    private javax.swing.JTextField txdatadn;
    private javax.swing.JTextField txendereco;
    private javax.swing.JLabel txlDnasci;
    private javax.swing.JTextField txnome;
    private javax.swing.JTextField txnr;
    private javax.swing.JTextField txsalario;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txturno;
    private javax.swing.JTextField txur;
    // End of variables declaration//GEN-END:variables
}
