/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Atualisas;

import Entrad.menuprincipal;
import TradutorDAO.AcessoDAO;
import TradutorDAO.ClienteDAO;
import TradutorDAO.PessoaDAO;
import classes.Pessoa;
import classes.cliente;
import classes.endereco;
import conexao.conexaoBanco;
import java.sql.Connection;
import java.util.ArrayList;

/**
 *
 * @author EEQS Lab02
 */
public class AtulCli extends javax.swing.JFrame {
    
ArrayList<endereco> endereco = new ArrayList<>();
    ArrayList<Pessoa> Pessoa = new ArrayList<>();
    ArrayList<cliente> cliente = new ArrayList<>();
    /**
     * Creates new form AtuCliente
     */
    public AtulCli() {
       
         initComponents();
         PessoaDAO psd = new PessoaDAO();
         Pessoa p = new Pessoa();
         endereco end = new endereco();

        // end.setCodigo(psd.UltResistroEndereco()+"");
        
         txcpf.setText(p.getCpf());
        txdatadn.setText(p.getDatanasc());
        txnome.setText(p.getNome());
        txTelefone.setText(p.getTelefone());
        
        txbairro.setText(end.getBairro());
        txcep.setText(end.getCep());
        txcidade.setText(end.getCidade());
        txcpf.setText(end.getFkcpf()+"");
        txendereco.setText(end.getEndereco());
        txnr.setText(end.getNumerResiden());
        txur.setText(end.getUr());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelcadastro = new javax.swing.JPanel();
        labelcadastrocliente = new javax.swing.JLabel();
        labelnomeclient = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        labelcpf = new javax.swing.JLabel();
        labelcidade = new javax.swing.JLabel();
        labelUR = new javax.swing.JLabel();
        labelEndere = new javax.swing.JLabel();
        labelBairr = new javax.swing.JLabel();
        labelNumeResi = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        txnome = new javax.swing.JTextField();
        txdatadn = new javax.swing.JTextField();
        txcpf = new javax.swing.JTextField();
        txur = new javax.swing.JTextField();
        txbairro = new javax.swing.JTextField();
        txcidade = new javax.swing.JTextField();
        txendereco = new javax.swing.JTextField();
        txnr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txcep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txTelefone = new javax.swing.JTextField();
        tbAtua = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txsenha = new javax.swing.JTextField();
        txlogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelcadastro.setBackground(new java.awt.Color(255, 255, 204));
        painelcadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelcadastrocliente.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labelcadastrocliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcadastrocliente.setText("ATUALIZAR");

        labelnomeclient.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelnomeclient.setText("NOME:");

        lb.setText("DATA DE NASCIMENTO:");

        labelcpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcpf.setText("CPF/CNPJ:");

        labelcidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcidade.setText("CIDADE:");

        labelUR.setText("UR:");

        labelEndere.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEndere.setText("ENDEREÇO:");

        labelBairr.setText("BAIRRO:");

        labelNumeResi.setText("NUMERO RESIDENCIAL:");

        btPesquisar.setBackground(new java.awt.Color(204, 102, 255));
        btPesquisar.setText("pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        txnome.setEditable(false);
        txnome.setBackground(new java.awt.Color(204, 153, 255));

        txdatadn.setEditable(false);
        txdatadn.setBackground(new java.awt.Color(204, 153, 255));
        txdatadn.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txdatadnCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        txcpf.setBackground(new java.awt.Color(204, 153, 255));

        txur.setEditable(false);
        txur.setBackground(new java.awt.Color(204, 153, 255));

        txbairro.setEditable(false);
        txbairro.setBackground(new java.awt.Color(204, 153, 255));

        txcidade.setEditable(false);
        txcidade.setBackground(new java.awt.Color(204, 153, 255));
        txcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcidadeActionPerformed(evt);
            }
        });

        txendereco.setEditable(false);
        txendereco.setBackground(new java.awt.Color(204, 153, 255));

        txnr.setEditable(false);
        txnr.setBackground(new java.awt.Color(204, 153, 255));

        jLabel2.setText("CEP:");

        txcep.setEditable(false);
        txcep.setBackground(new java.awt.Color(204, 153, 255));

        jButton1.setBackground(new java.awt.Color(204, 102, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("TELEFONE:");

        txTelefone.setEditable(false);
        txTelefone.setBackground(new java.awt.Color(204, 153, 255));

        tbAtua.setBackground(new java.awt.Color(204, 102, 255));
        tbAtua.setText("Atualizar");
        tbAtua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAtuaActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(204, 102, 255));
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        txsenha.setEditable(false);
        txsenha.setBackground(new java.awt.Color(204, 153, 255));

        txlogin.setEditable(false);
        txlogin.setBackground(new java.awt.Color(204, 153, 255));

        jLabel3.setText("Login:");

        jLabel4.setText("Senha:");

        javax.swing.GroupLayout painelcadastroLayout = new javax.swing.GroupLayout(painelcadastro);
        painelcadastro.setLayout(painelcadastroLayout);
        painelcadastroLayout.setHorizontalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelcadastrocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelEndere, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(labelcidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelBairr))
                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelcadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txendereco)
                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                            .addComponent(txbairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                            .addComponent(txsenha))
                                        .addGap(18, 18, 18)
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txcep, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelUR)
                                            .addComponent(txcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelNumeResi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txnr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tbAtua)
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addComponent(labelcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 90, Short.MAX_VALUE))))
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPesquisar)
                            .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelcadastroLayout.createSequentialGroup()
                                    .addComponent(lb)
                                    .addGap(18, 18, 18)
                                    .addComponent(txdatadn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelcadastroLayout.createSequentialGroup()
                                    .addComponent(labelnomeclient, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txnome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btExcluir)
                .addGap(106, 106, 106))
        );
        painelcadastroLayout.setVerticalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelcadastrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcpf)
                    .addComponent(txcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addGap(19, 19, 19)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnomeclient)
                    .addComponent(txnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUR)
                    .addComponent(txur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeResi)
                    .addComponent(txnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb)
                    .addComponent(txdatadn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcidade)
                    .addComponent(txcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndere)
                    .addComponent(txendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBairr)
                    .addComponent(txcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(tbAtua)
                    .addComponent(btExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        txTelefone.setText("");
        txbairro.setText("");
        txcep.setText("");
        txcidade.setText("");
        txdatadn.setText("");
        txendereco.setText("");
        txnome.setText("");
        txnr.setText("");
        txur.setText("");

        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);
        PessoaDAO psd = new PessoaDAO();

        Pessoa p  = new Pessoa();
        endereco end = new endereco();

        
        
        p = psd.buscarPessoa(txcpf.getText());
        end = psd.buscarEnderecoPes(txcpf.getText());

        
        txcpf.setText(p.getCpf());
        txdatadn.setText(p.getDatanasc());
        txnome.setText(p.getNome());
        txTelefone.setText(p.getTelefone());
        txsenha.setText(p.getSenha());
        txlogin.setText(p.getLogin());
        
        txbairro.setText(end.getBairro());
        txcep.setText(end.getCep());
        txcidade.setText(end.getCidade());
        txcpf.setText(end.getFkcpf()+"");
        txendereco.setText(end.getEndereco());
        txnr.setText(end.getNumerResiden());
        txur.setText(end.getUr());

        
        txcpf.setEditable(false);

        txTelefone.setEditable(true);
        txbairro.setEditable(true);
        txcep.setEditable(true);
        txcidade.setEditable(true);
        txdatadn.setEditable(true);
        txlogin.setEditable(true);
        txendereco.setEditable(true);
        txnome.setEditable(true);
        txnr.setEditable(true);
        txsenha.setEditable(true);
        txur.setEditable(true);


    }//GEN-LAST:event_btPesquisarActionPerformed

    private void txdatadnCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txdatadnCaretPositionChanged

    }//GEN-LAST:event_txdatadnCaretPositionChanged

    private void txcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcidadeActionPerformed

    }//GEN-LAST:event_txcidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    menuprincipal mp = new menuprincipal();
    mp.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbAtuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAtuaActionPerformed
        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);
        PessoaDAO psd = new PessoaDAO();

        Pessoa p  = new Pessoa();
        endereco end = new endereco();

        p.setDatanasc(txdatadn.getText());
        p.setLogin(txlogin.getText());
        p.setNome(txnome.getText());
        p.setSenha(txsenha.getText());
        p.setTelefone(txTelefone.getText());
        
        p.setCpf(txcpf.getText());    
        end.setFkcpf(txcpf.getText());        
        
        end.setBairro(txbairro.getText());
        end.setCep(txcep.getText());
        end.setCidade(txcidade.getText());
        end.setEndereco(txendereco.getText());
        end.setNumerResiden(txnr.getText());
        end.setUr(txur.getText());
        
        Pessoa.add(p);
        endereco.add(end);
    
    
   psd.AtualEnd(end);
   psd.AtualPessoa(p);
  
        
        
    }//GEN-LAST:event_tbAtuaActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
     
        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);

        ClienteDAO cld = new ClienteDAO();
        
        
        if(cld.ExcluirPessoa(txcpf.getText())){

        txTelefone.setText("");
        txbairro.setText("");
        txcep.setText("");
        txcidade.setText("");
        txdatadn.setText("");
        txendereco.setText("");
        txnome.setText("");
        txnr.setText("");
        txur.setText("");
        txcpf.setText("");
        txsenha.setText("");
        txlogin.setText("");
        
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtulCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtulCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtulCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtulCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtulCli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    public static javax.swing.JButton btPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelBairr;
    private javax.swing.JLabel labelEndere;
    private javax.swing.JLabel labelNumeResi;
    private javax.swing.JLabel labelUR;
    private javax.swing.JLabel labelcadastrocliente;
    private javax.swing.JLabel labelcidade;
    private javax.swing.JLabel labelcpf;
    private javax.swing.JLabel labelnomeclient;
    private javax.swing.JLabel lb;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JButton tbAtua;
    public static javax.swing.JTextField txTelefone;
    public static javax.swing.JTextField txbairro;
    public static javax.swing.JTextField txcep;
    public static javax.swing.JTextField txcidade;
    public static javax.swing.JTextField txcpf;
    public static javax.swing.JTextField txdatadn;
    public static javax.swing.JTextField txendereco;
    public static javax.swing.JTextField txlogin;
    public static javax.swing.JTextField txnome;
    public static javax.swing.JTextField txnr;
    public static javax.swing.JTextField txsenha;
    public static javax.swing.JTextField txur;
    // End of variables declaration//GEN-END:variables
}
