

package Chefa;


import TradutorDAO.CauculadoraDaoChef;
import TradutorDAO.AcessoDAO;
import TradutorDAO.CompraDao;
import static TradutorDAO.CompraDao.o;
import TradutorDAO.DataDao;
import classes.Comprapeq;
import classes.datas;
import conexao.conexaoBanco;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Robot;







/**
 *
 * @author Vivian Raquel
 */
public class SofrendoNaCalculadChef extends javax.swing.JFrame {

    private CauculadoraDaoChef cal;
    int enter = 0;

    
    
    /**
     * Creates new form SofrendoNaCalculadora
     */
    public SofrendoNaCalculadChef() {
        initComponents();
        DataDao ddao = new DataDao();
        
        ddao.data();
        setLocationRelativeTo(null);
        ListaNomes.setVisible(false);
        ListaNomesCli.setVisible(false);
        this.cal = new CauculadoraDaoChef();
        float i = 0;
        txCalculo.setText(i+"");
        jpaiPesqPes.setVisible(false);
        
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listQtddP = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        txNomep = new javax.swing.JTextField();
        txpreco1 = new javax.swing.JTextField();
        ListaNomes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        listNomesAnt = new javax.swing.JList<>();
        txCalculo = new javax.swing.JTextField();
        txQtddP = new javax.swing.JTextField();
        labNuList = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jpaiPesqPes = new javax.swing.JPanel();
        btSalCom = new javax.swing.JButton();
        txNomeC = new javax.swing.JTextField();
        ListaNomesCli = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcular");
        setBackground(new java.awt.Color(255, 102, 102));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 32767, 32767));
        setMinimumSize(new java.awt.Dimension(1310, 690));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        listQtddP.setBackground(new java.awt.Color(51, 0, 0));
        listQtddP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        listQtddP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listQtddP.setForeground(new java.awt.Color(255, 255, 255));
        listQtddP.setAutoscrolls(false);
        listQtddP.setSelectionBackground(new java.awt.Color(255, 255, 255));
        listQtddP.setSelectionForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(listQtddP);
        listQtddP.setBounds(1190, 320, 100, 230);
        listQtddP.getAccessibleContext().setAccessibleDescription("");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 640, 110, 40);

        txNomep.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txNomep.setForeground(new java.awt.Color(204, 0, 0));
        txNomep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txNomep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txNomepMouseClicked(evt);
            }
        });
        txNomep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomepActionPerformed(evt);
            }
        });
        txNomep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txNomepKeyReleased(evt);
            }
        });
        jPanel1.add(txNomep);
        txNomep.setBounds(40, 20, 860, 60);

        txpreco1.setBackground(new java.awt.Color(51, 0, 0));
        txpreco1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txpreco1.setForeground(new java.awt.Color(255, 255, 255));
        txpreco1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        txpreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpreco1ActionPerformed(evt);
            }
        });
        jPanel1.add(txpreco1);
        txpreco1.setBounds(970, 610, 320, 60);

        ListaNomes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ListaNomes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListaNomes.setForeground(new java.awt.Color(204, 0, 0));
        ListaNomes.setSelectionBackground(new java.awt.Color(204, 0, 51));
        ListaNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaNomesMouseClicked(evt);
            }
        });
        jPanel1.add(ListaNomes);
        ListaNomes.setBounds(40, 80, 860, 170);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("+ Quantos?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 110, 80, 16);

        listNomesAnt.setBackground(new java.awt.Color(51, 0, 0));
        listNomesAnt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        listNomesAnt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listNomesAnt.setForeground(new java.awt.Color(255, 255, 255));
        listNomesAnt.setAutoscrolls(false);
        listNomesAnt.setSelectionBackground(new java.awt.Color(255, 255, 255));
        listNomesAnt.setSelectionForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(listNomesAnt);
        listNomesAnt.setBounds(840, 320, 350, 230);
        listNomesAnt.getAccessibleContext().setAccessibleDescription("");

        txCalculo.setBackground(new java.awt.Color(51, 0, 0));
        txCalculo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txCalculo.setForeground(new java.awt.Color(255, 255, 255));
        txCalculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(txCalculo);
        txCalculo.setBounds(840, 550, 450, 60);

        txQtddP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txQtddP.setForeground(new java.awt.Color(204, 0, 0));
        txQtddP.setText("1");
        txQtddP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txQtddP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txQtddPActionPerformed(evt);
            }
        });
        jPanel1.add(txQtddP);
        txQtddP.setBounds(100, 100, 60, 40);

        labNuList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labNuList.setForeground(new java.awt.Color(255, 255, 255));
        labNuList.setText("0");
        jPanel1.add(labNuList);
        labNuList.setBounds(1304, 420, 30, 30);

        jButton3.setText("Salvar Pessoa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(400, 640, 130, 40);

        jpaiPesqPes.setBackground(new java.awt.Color(153, 0, 0));
        jpaiPesqPes.setLayout(null);

        btSalCom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalCom.setForeground(new java.awt.Color(153, 0, 0));
        btSalCom.setText("Salvar Compra");
        btSalCom.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btSalCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalComActionPerformed(evt);
            }
        });
        jpaiPesqPes.add(btSalCom);
        btSalCom.setBounds(510, 220, 130, 30);

        txNomeC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txNomeC.setForeground(new java.awt.Color(204, 0, 0));
        txNomeC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txNomeC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txNomeCMouseClicked(evt);
            }
        });
        txNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeCActionPerformed(evt);
            }
        });
        txNomeC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txNomeCKeyReleased(evt);
            }
        });
        jpaiPesqPes.add(txNomeC);
        txNomeC.setBounds(20, 20, 680, 40);

        ListaNomesCli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ListaNomesCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListaNomesCli.setForeground(new java.awt.Color(204, 0, 0));
        ListaNomesCli.setSelectionBackground(new java.awt.Color(204, 0, 51));
        ListaNomesCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaNomesCliMouseClicked(evt);
            }
        });
        jpaiPesqPes.add(ListaNomesCli);
        ListaNomesCli.setBounds(20, 60, 680, 100);

        jPanel1.add(jpaiPesqPes);
        jpaiPesqPes.setBounds(80, 310, 720, 270);

        jButton4.setText("Salvar Pessoa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(570, 640, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1390, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    Comprapeq comp = new Comprapeq();

    String cliente;
    

    private void txNomepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomepActionPerformed
        ListaNomes.setVisible(false);
        enter=1;
        
        if(txNomep.isEditable()){
            this.cal.Pesquisa();
            
        }else {
            enter = 0;
            ListaNomes.setVisible(false);
       }
    }//GEN-LAST:event_txNomepActionPerformed

    private void txNomepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNomepKeyReleased
        if(enter==0){
            this.cal.Pesquisa();
        }else {
            enter = 0;
            ListaNomes.setVisible(false);
        }   
    }//GEN-LAST:event_txNomepKeyReleased

    private void ListaNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaNomesMouseClicked
        this.cal.LinhaClicada();
        this.cal.calcularTodo();
        ListaNomes.setVisible(false);

    }//GEN-LAST:event_ListaNomesMouseClicked

    private void txQtddPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txQtddPActionPerformed
        this.cal.calcularQProd();
    }//GEN-LAST:event_txQtddPActionPerformed

    private void txNomepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txNomepMouseClicked

    }//GEN-LAST:event_txNomepMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       ListaNomes.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    private void txpreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpreco1ActionPerformed

    }//GEN-LAST:event_txpreco1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        System.out.print("quantidade de produtos: \n");
        
        int oz=0;
        while(oz<=3){
            
            listNomesAnt.setSelectedIndex(oz);
            listQtddP.setSelectedIndex(oz);
            System.out.print("\n"+listQtddP.getSelectedValue());
        
            oz++;
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btSalComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalComActionPerformed
        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);
        
        CauculadoraDaoChef calChef = new CauculadoraDaoChef();
        CompraDao comDa = new CompraDao();
        DataDao dt = new DataDao();
        datas dts = new datas();
        Date datas = new Date();
        
        
        SimpleDateFormat formH = new SimpleDateFormat ("yyyy/MM/dd");
        String dat = (formH.format(datas)+"");
        comp.setFkdatas(dat);

        
        int p = Integer.parseInt(labNuList.getText());
        p--;
        
        
        if(p >= 0){
        
            while(p>=0){
        
                comp.setCodigo(comDa.UltResistroComp()+"");
                comp.setFkpessoa(cliente);
        
                comDa.inserirComp(comp);

                p--;

        }
// se tudo der certo é necessario zerar a lista e o preco dos produtos
        } 
        else {
            JOptionPane.showMessageDialog(null,"Erro ao buscar os dados do Produto","ERRO,", JOptionPane.CLOSED_OPTION);
      }
        
        

    // ESSE BOTÃO VAI MANDAR A PESSOA PARA UMA PROXIMA JANELA ONDE SERÁ POSSIVEL VISUALIZAR O PREÇO TOTAL, VER A LISTA DE COMPRAS, CALCULAR O TROCO
    // CALCULAR O QUANTO FOI GANHO NESTA COMPRA, O QUAO PERTO ESTAR DE PAGAR A DIVIDA (Da Compra Dos Produtos E Outras Despesas (como aluguel,
    // energia, etc)), SALVANDO TAMBEM no BD O QUE FOI USADO PARA PAGAR A COMPRA (Avista, cartão, parcelado, dinero vivo) e
    // SE FOI ENTREGUE NA CASA DA PESSOA OU SE FOI ELA QUE LEVOU

    //LEMBRANDO QUE TUDO ISSO SERÁ FEITO ATRAVEZ DE DIVERSOS METODOS E NEM TODOS FICARAM APARENTES PARA O FUNCIONARIO NA ABA QUE ESSE BOTÃO LEVARA
    // MAS TUDO ISSO FICA VISIVEL PARA MIM EM ABAS DIFERENTES NO MENU PRINCIPAL :)

        jpaiPesqPes.setVisible(false);
    }//GEN-LAST:event_btSalComActionPerformed

    private void txNomeCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txNomeCMouseClicked
        cliente= ( this.cal.LinhaClicadaClient());
        ListaNomes.setVisible(false);
    }//GEN-LAST:event_txNomeCMouseClicked

    private void txNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeCActionPerformed
        ListaNomes.setVisible(false);
        enter=1;

        if(txNomeC.isEditable()){
            this.cal.PesquisaClient();

        }else {
            enter = 0;
            ListaNomes.setVisible(false);
        }
    }//GEN-LAST:event_txNomeCActionPerformed

    private void txNomeCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNomeCKeyReleased
        if(enter==0){
            this.cal.PesquisaClient();
        }else {
            enter = 0;
            ListaNomes.setVisible(false);
        }
    }//GEN-LAST:event_txNomeCKeyReleased

    private void ListaNomesCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaNomesCliMouseClicked
        cliente= ( this.cal.LinhaClicadaClient());
        ListaNomes.setVisible(false);
    }//GEN-LAST:event_ListaNomesCliMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jpaiPesqPes.setVisible(true);   
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SofrendoNaCalculadChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SofrendoNaCalculadChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SofrendoNaCalculadChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SofrendoNaCalculadChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SofrendoNaCalculadChef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList<String> ListaNomes;
    public static javax.swing.JList<String> ListaNomesCli;
    private javax.swing.JButton btSalCom;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpaiPesqPes;
    public static javax.swing.JLabel labNuList;
    public static javax.swing.JList<String> listNomesAnt;
    public static javax.swing.JList<String> listQtddP;
    public static javax.swing.JTextField txCalculo;
    public static javax.swing.JTextField txNomeC;
    public static javax.swing.JTextField txNomep;
    public static javax.swing.JTextField txQtddP;
    public static javax.swing.JTextField txpreco1;
    // End of variables declaration//GEN-END:variables
}
