/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Janelas;

import TradutorDAO.CauculadoraDaoChef;

/**
 *
 * @author User1
 */
public class InformaçõesCompra extends javax.swing.JFrame {
    private CauculadoraDaoChef cal;
    int enter = 0;
    /**
     * Creates new form InformaçõesCompra
     */
    public InformaçõesCompra() {
        initComponents();
        setLocationRelativeTo(null);
        ListaNomes.setVisible(false);
        this.cal = new CauculadoraDaoChef();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txNomeC = new javax.swing.JTextField();
        ListaNomes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 220, 90, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Salvar Compra");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(510, 220, 130, 30);

        txNomeC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txNomeC.setForeground(new java.awt.Color(204, 0, 0));
        txNomeC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txNomeC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txNomeCMouseClicked(evt);
            }
        });
        txNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeCActionPerformed(evt);
            }
        });
        txNomeC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txNomeCKeyReleased(evt);
            }
        });
        jPanel2.add(txNomeC);
        txNomeC.setBounds(20, 20, 680, 40);

        ListaNomes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ListaNomes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListaNomes.setForeground(new java.awt.Color(204, 0, 0));
        ListaNomes.setSelectionBackground(new java.awt.Color(204, 0, 51));
        ListaNomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaNomesMouseClicked(evt);
            }
        });
        jPanel2.add(ListaNomes);
        ListaNomes.setBounds(20, 60, 680, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaNomesMouseClicked
        this.cal.LinhaClicadaClient();
        ListaNomes.setVisible(false);
    }//GEN-LAST:event_ListaNomesMouseClicked

    private void txNomeCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNomeCKeyReleased
        if(enter==0){
            this.cal.PesquisaClient();
        }else {
            enter = 0;
            ListaNomes.setVisible(false);
        }
    }//GEN-LAST:event_txNomeCKeyReleased

    private void txNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeCActionPerformed
        ListaNomes.setVisible(false);
        enter=1;

        if(txNomeC.isEditable()){
            this.cal.PesquisaClient();

        }else {
            enter = 0;
            ListaNomes.setVisible(false);
        }
    }//GEN-LAST:event_txNomeCActionPerformed

    private void txNomeCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txNomeCMouseClicked
        this.cal.LinhaClicadaClient();
        ListaNomes.setVisible(false);
    }//GEN-LAST:event_txNomeCMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        this.dispose();
        
        
      
        

        // ESSE BOTÃO VAI MANDAR A PESSOA PARA UMA PROXIMA JANELA ONDE SERÁ POSSIVEL VISUALIZAR O PREÇO TOTAL, VER A LISTA DE COMPRAS, CALCULAR O TROCO
        // CALCULAR O QUANTO FOI GANHO NESTA COMPRA, O QUAO PERTO ESTAR DE PAGAR A DIVIDA (Da Compra Dos Produtos E Outras Despesas (como aluguel,
        // energia, etc)), TAMBEM DARA PARA DAR BAIXA NO ESTOQUE E SALVAR A COMPRA NO BANCO DE DADOS COM UMA CHAVE ESTRANGEIRA (Foreing Key) REFERENTE
        // A TABELA PESSOA (Ao Cliente Que Comprou) SALVANDO TAMBEM O QUE FOI USADO PARA PAGAR A COMPRA (Avista, cartão, parcelado, dinero vivo) e
        // SE FOI ENTREGUE NA CASA DA PESSOA OU SE FOI ELA QUE LEVOU

        //LEMBRANDO QUE TUDO ISSO SERÁ FEITO ATRAVEZ DE DIVERSOS METODOS E NEM TODOS FICARAM APARENTES PARA O FUNCIONARIO NA ABA QUE ESSE BOTÃO LEVARA
        // MAS TUDO ISSO FICA VISIVEL PARA MIM EM ABAS DIFERENTES NO MENU PRINCIPAL :)
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformaçõesCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformaçõesCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformaçõesCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformaçõesCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformaçõesCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList<String> ListaNomes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txNomeC;
    // End of variables declaration//GEN-END:variables
}
