/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadas;

import Entrad.menuprincipal;
import TradutorDAO.AcessoDAO;
import TradutorDAO.EstoqueDAO;
import classes.Categoria;
import classes.estoque;
import conexao.conexaoBanco;
import java.awt.Color;
import java.sql.Connection;
import java.util.ArrayList;


/**
 *
 * @author User1
 */
public class CadastroProduto extends javax.swing.JFrame {
    ArrayList<estoque> estoque = new ArrayList<>();//transformar a tabela pessoa em lista//
    ArrayList<Categoria> Categoria = new ArrayList<>();//transformar a tabela aluno (que é separada em dados) em lista//
    
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        
        EstoqueDAO esdao = new EstoqueDAO();
        txCodigo.setText(esdao.UltResistroEstoque()+"");
        
        txNovCate.setVisible(false);
        labNovCate.setVisible(false);
        btSalNovCate.setVisible(false);
        
        for(Categoria cate : esdao.ListaCate()){ //Alinha a cima chama a classe pessoa e atualiza os dados listando os
            //itens que foi buscado no banco de dados, atravez da funçao listar pessoa
            jcbxCate.addItem(cate.getCategoria());
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txnomeP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        txpreco = new javax.swing.JTextField();
        txprecodep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btSalvarProduto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jcbxCate = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pnNovCate = new javax.swing.JPanel();
        labNovCate = new javax.swing.JLabel();
        txNovCate = new javax.swing.JTextField();
        btSalNovCate = new javax.swing.JButton();
        txVenci = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel2.setText("Nome do Produto:");

        txnomeP.setBackground(new java.awt.Color(153, 255, 153));

        jLabel3.setText("Codigo:");

        txCodigo.setBackground(new java.awt.Color(153, 255, 153));

        jLabel4.setText("Preço:");

        txpreco.setBackground(new java.awt.Color(153, 255, 153));
        txpreco.setToolTipText(" .   ");

        txprecodep.setBackground(new java.awt.Color(153, 255, 153));

        jLabel5.setText("Preço de compra:");

        jLabel6.setText("Categoria:");

        btSalvarProduto.setBackground(new java.awt.Color(51, 255, 51));
        btSalvarProduto.setText("Salvar");
        btSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarProdutoActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CADASTRO DE PRODUTO:");

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcbxCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxCateActionPerformed(evt);
            }
        });

        jLabel8.setText("Faltando uma categoria?");

        jButton2.setText("Clica aqui.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pnNovCate.setBackground(new java.awt.Color(255, 204, 255));

        labNovCate.setText("Nova Categoria:");

        txNovCate.setBackground(new java.awt.Color(153, 255, 153));

        btSalNovCate.setText("Salvar");
        btSalNovCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalNovCateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNovCateLayout = new javax.swing.GroupLayout(pnNovCate);
        pnNovCate.setLayout(pnNovCateLayout);
        pnNovCateLayout.setHorizontalGroup(
            pnNovCateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNovCateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labNovCate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txNovCate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSalNovCate)
                .addGap(49, 49, 49))
        );
        pnNovCateLayout.setVerticalGroup(
            pnNovCateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNovCateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNovCateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNovCate)
                    .addComponent(txNovCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalNovCate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txVenci.setBackground(new java.awt.Color(153, 255, 153));

        jLabel9.setText("Vencimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbxCate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(btSalvarProduto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(199, 199, 199)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnNovCate, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txnomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txpreco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txVenci, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txprecodep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txnomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txprecodep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txVenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcbxCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSalvarProduto))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel8)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnNovCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarProdutoActionPerformed
   
        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);
        estoque est  = new estoque();
        Categoria p  = new Categoria();

        EstoqueDAO esdao = new EstoqueDAO();

        p.setCategoria(jcbxCate.getSelectedItem()+"");
        String po= (esdao.buscarCategoria(jcbxCate.getSelectedItem()+"")+"");

        est.setCodigo(Integer.parseInt(txCodigo.getText()));
        est.setNOMEP(txnomeP.getText());
        est.setPreco(Float.parseFloat(txpreco.getText()));
        est.setFkcodigo(jcbxCate.getSelectedIndex());
        est.setVencimento(txVenci.getText());

        estoque.add(est);//cria uma "lista" com todos os dados p.set{...}
        Categoria.add(p);

        esdao.inserirEstoque(est,po);

        txnomeP.setText("");
        txpreco.setText("");
        txprecodep.setText("");
        txVenci.setText("");
       
        int v = (Integer.parseInt(txCodigo.getText()));
        v ++;
        txCodigo.setText(v +"");
     
    
    }//GEN-LAST:event_btSalvarProdutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menuprincipal mp = new menuprincipal();
        mp.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbxCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxCateActionPerformed

        
        // Mudança de ideias esse JcomboBox tera de buscar as categorias do banco de dados
        //PROBLEMA: ele vai pegar repetido portanto você Vivian tera de mudar o banco de dados 
        // Para que cada produto tenha uma categoria (categoria seria a primary?)
        
        
        int NuJcombx = (jcbxCate.getSelectedIndex());
        
        //pode usar a variavel ou o codigo direto;
        
        if(jcbxCate.getSelectedIndex() == 0 ){// 00 , verde, vermelho
            jcbxCate.setBackground(Color.orange);}
        if(jcbxCate.getSelectedIndex() == 1 ){
            jcbxCate.setBackground(Color.cyan);}
        if(jcbxCate.getSelectedIndex() == 2 ){
            jcbxCate.setBackground(Color.yellow);}
        if(jcbxCate.getSelectedIndex() == 3 ){
            jcbxCate.setBackground(Color.getHSBColor(408, 200, 211));}
        if(jcbxCate.getSelectedIndex() == 4 ){
            jcbxCate.setBackground(Color.green);}
        if(jcbxCate.getSelectedIndex() == 5 ){
            jcbxCate.setBackground(Color.RED);}
        if(NuJcombx == 6 ){
            jcbxCate.setBackground(Color.lightGray);}
        if(NuJcombx == 7 ){
            jcbxCate.setBackground(Color.PINK);}
        if(NuJcombx == 8 ){
            jcbxCate.setBackground(Color.DARK_GRAY);}
        if(NuJcombx == 9 ){
            jcbxCate.setBackground(Color.magenta);}
        
    }//GEN-LAST:event_jcbxCateActionPerformed

    int v = 1;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        v++;
                
        v = v % 2;
        System.out.print(v);
        if(v == 0){
        
            txNovCate.setVisible(true);
            labNovCate.setVisible(true);
            btSalNovCate.setVisible(true);}
        
        else {
            
            txNovCate.setVisible(false);
            labNovCate.setVisible(false);
            btSalNovCate.setVisible(false);
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btSalNovCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalNovCateActionPerformed
        
        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);
        
        Categoria cate = new Categoria();
        EstoqueDAO esdao = new EstoqueDAO();
        
        cate.setID(esdao.UltResistroCatego()); 
        cate.setCategoria(txNovCate.getText());
        
        esdao.inserirCategoria(cate);

        jcbxCate.addItem(cate.getCategoria());

        
    }//GEN-LAST:event_btSalNovCateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalNovCate;
    private javax.swing.JButton btSalvarProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    public static javax.swing.JComboBox<String> jcbxCate;
    private javax.swing.JLabel labNovCate;
    private javax.swing.JPanel pnNovCate;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txNovCate;
    private javax.swing.JTextField txVenci;
    private javax.swing.JTextField txnomeP;
    private javax.swing.JTextField txpreco;
    private javax.swing.JTextField txprecodep;
    // End of variables declaration//GEN-END:variables
}
