package Cadas;

import Entrad.menuprincipal;
import TradutorDAO.AcessoDAO;
import TradutorDAO.ClienteDAO;
import TradutorDAO.PessoaDAO;
import classes.Pessoa;
import classes.cliente;
import classes.endereco;
import conexao.conexaoBanco;
import java.sql.Connection;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User1
 */
public class CadastroCliente extends javax.swing.JFrame {
    
    ArrayList<cliente> cliente = new ArrayList<>();//transformar a tabela pessoa em lista//
    ArrayList<Pessoa> Pessoa = new ArrayList<>();//transformar a tabela pessoa em lista//
    ArrayList<endereco> endereco = new ArrayList<>();//transformar a tabela endereco (que é separada em dados) em lista//


    
    
    /**
     * Creates new form visualizacao
     */
    public CadastroCliente() {
        
        initComponents();
        PessoaDAO pdao = new PessoaDAO();
        
        labLogin.setVisible(false);
        labSenha.setVisible(false);
        txLogin.setVisible(false);
        txSenha.setVisible(false);
        txcodigo.setVisible(false);
        
        txcodigo.setText(pdao.UltResistroEndereco()+"");
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        painelcadastro = new javax.swing.JPanel();
        labelcadastrocliente = new javax.swing.JLabel();
        labelnomeclient = new javax.swing.JLabel();
        labelDnasci = new javax.swing.JLabel();
        labelcpf = new javax.swing.JLabel();
        labeltelefone = new javax.swing.JLabel();
        labelcidade = new javax.swing.JLabel();
        labelUR = new javax.swing.JLabel();
        labelEndere = new javax.swing.JLabel();
        labelBairr = new javax.swing.JLabel();
        labelNumeResi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txNome = new javax.swing.JTextField();
        txDatNasci1 = new javax.swing.JTextField();
        txCPF = new javax.swing.JTextField();
        txTeleCelular = new javax.swing.JTextField();
        txUR = new javax.swing.JTextField();
        txBairro = new javax.swing.JTextField();
        txCidade = new javax.swing.JTextField();
        txEndereco = new javax.swing.JTextField();
        txNcasa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txCep = new javax.swing.JTextField();
        labLogin = new javax.swing.JLabel();
        txLogin = new javax.swing.JTextField();
        labSenha = new javax.swing.JLabel();
        txSenha = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        txcodigo = new javax.swing.JTextField();
        txDatNasci = new javax.swing.JFormattedTextField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 240, 240));

        painelcadastro.setBackground(new java.awt.Color(153, 255, 153));
        painelcadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelcadastrocliente.setBackground(new java.awt.Color(102, 255, 255));
        labelcadastrocliente.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labelcadastrocliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcadastrocliente.setText("CADASTRO");
        labelcadastrocliente.setToolTipText("");
        labelcadastrocliente.setBorder(new javax.swing.border.MatteBorder(null));

        labelnomeclient.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelnomeclient.setText("NOME:");

        labelDnasci.setText("DATA DE NASCIMENTO:");

        labelcpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcpf.setText("CPF/CNPJ:");

        labeltelefone.setText("TELEFONE CELULAR:");

        labelcidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelcidade.setText("CIDADE:");

        labelUR.setText("UR:");

        labelEndere.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEndere.setText("ENDEREÇO:");

        labelBairr.setText("BAIRRO:");

        labelNumeResi.setText("NUMERO RESIDENCIAL:");

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txNome.setBackground(new java.awt.Color(255, 204, 204));

        txDatNasci1.setBackground(new java.awt.Color(255, 204, 204));
        txDatNasci1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txDatNasci1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        txCPF.setBackground(new java.awt.Color(255, 204, 204));

        txTeleCelular.setBackground(new java.awt.Color(255, 204, 204));

        txUR.setBackground(new java.awt.Color(255, 204, 204));

        txBairro.setBackground(new java.awt.Color(255, 204, 204));

        txCidade.setBackground(new java.awt.Color(255, 204, 204));

        txEndereco.setBackground(new java.awt.Color(255, 204, 204));

        txNcasa.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("CEP:");

        txCep.setBackground(new java.awt.Color(255, 204, 204));

        labLogin.setText("Login:");

        txLogin.setBackground(new java.awt.Color(255, 204, 204));

        labSenha.setText("Senha:");

        txSenha.setBackground(new java.awt.Color(255, 204, 204));

        jCheckBox1.setBackground(new java.awt.Color(255, 204, 204));
        jCheckBox1.setText("  Deseja ter acesso ao aplicativo?");
        jCheckBox1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jCheckBox1AncestorRemoved(evt);
            }
        });
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        txcodigo.setBackground(new java.awt.Color(255, 204, 204));

        txDatNasci.setBackground(new java.awt.Color(255, 204, 204));
        try {
            txDatNasci.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout painelcadastroLayout = new javax.swing.GroupLayout(painelcadastro);
        painelcadastro.setLayout(painelcadastroLayout);
        painelcadastroLayout.setHorizontalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelcadastrocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelcadastroLayout.createSequentialGroup()
                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelDnasci)
                                    .addComponent(labelnomeclient, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEndere, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelBairr)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txDatNasci1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(labeltelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txTeleCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(labelUR)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txUR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelNumeResi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txNcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                                .addComponent(txBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labLogin))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelcadastroLayout.createSequentialGroup()
                                                .addComponent(txCep, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labSenha)))
                                        .addGap(18, 18, 18)
                                        .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(painelcadastroLayout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(painelcadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jCheckBox1)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelcadastroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txDatNasci, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        painelcadastroLayout.setVerticalGroup(
            painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelcadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelcadastrocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnomeclient)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDnasci)
                    .addComponent(txDatNasci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltelefone)
                    .addComponent(txTeleCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelcpf)
                    .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelUR)
                        .addComponent(txUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNumeResi)
                        .addComponent(txNcasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcidade)
                    .addComponent(txCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndere)
                    .addComponent(txEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBairr)
                    .addComponent(labLogin)
                    .addComponent(txLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labSenha)
                    .addComponent(txSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(txcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txDatNasci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        txcodigo.getAccessibleContext().setAccessibleParent(txcodigo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelcadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txDatNasci1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txDatNasci1CaretPositionChanged
  
    }//GEN-LAST:event_txDatNasci1CaretPositionChanged
 
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){

            labLogin.setVisible(true);
            labSenha.setVisible(true);
            txLogin.setVisible(true);
            txSenha.setVisible(true);  
        }else{
            labLogin.setVisible(false);
            labSenha.setVisible(false);
            txLogin.setVisible(false);
            txSenha.setVisible(false);  
        }
      
        
// Pergunte ao professor como fazer para que quando o quadrado desmarcado os lab's e tx's a cima desapareçam
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCheckBox1AncestorRemoved


    }//GEN-LAST:event_jCheckBox1AncestorRemoved
// Não deram certo!!!!! estava tentando fazer o do comentario a cima
    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
 
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
   
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Connection con = conexaoBanco.AbrirConexao();
        AcessoDAO ac = new AcessoDAO (con);
        Pessoa p = new Pessoa();
        endereco end = new endereco();
        cliente cl = new cliente();

        PessoaDAO psd = new PessoaDAO();
        ClienteDAO cldao = new ClienteDAO();

        p.setCpf(txCPF.getText());//1
        p.setNome(txNome.getText());//2
        p.setDatanasc(txDatNasci1.getText());//3
        p.setLogin(txLogin.getText());//4
        p.setSenha(txSenha.getText());//5
        p.setTelefone(txTeleCelular.getText());//6
        
        end.setCodigo(txcodigo.getText());//1
        end.setFkcpf(txCPF.getText());//2
        end.setCep(txCep.getText());//3
        end.setBairro(txBairro.getText());//4
        end.setEndereco(txEndereco.getText());//5
        end.setCidade(txCidade.getText());//6
        end.setNumerResiden(txNcasa.getText());//7
        end.setUr(txUR.getText());//8

        cl.setFkcpf(txCPF.getText());//1
        cl.setMatricula(cldao.UltResistroCliente()+"");//2

        Pessoa.add(p);//cria uma "lista" com todos os dados p.set{...}
        endereco.add(end);
        cliente.add(cl);

        psd.inserirPessoa(p);
        psd.inserirEndereco(end);
        cldao.inserirCliente(cl);

        menuprincipal mp = new menuprincipal();
        mp.setVisible(true);
        this.dispose();
 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labLogin;
    private javax.swing.JLabel labSenha;
    private javax.swing.JLabel labelBairr;
    private javax.swing.JLabel labelDnasci;
    private javax.swing.JLabel labelEndere;
    private javax.swing.JLabel labelNumeResi;
    private javax.swing.JLabel labelUR;
    private javax.swing.JLabel labelcadastrocliente;
    private javax.swing.JLabel labelcidade;
    private javax.swing.JLabel labelcpf;
    private javax.swing.JLabel labelnomeclient;
    private javax.swing.JLabel labeltelefone;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JTextField txBairro;
    private javax.swing.JTextField txCPF;
    private javax.swing.JTextField txCep;
    private javax.swing.JTextField txCidade;
    private javax.swing.JFormattedTextField txDatNasci;
    private javax.swing.JTextField txDatNasci1;
    private javax.swing.JTextField txEndereco;
    private javax.swing.JTextField txLogin;
    private javax.swing.JTextField txNcasa;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txSenha;
    private javax.swing.JTextField txTeleCelular;
    private javax.swing.JTextField txUR;
    private javax.swing.JTextField txcodigo;
    // End of variables declaration//GEN-END:variables
}
